#!/bin/sh

./scripts/source

if [ `uname` = "Darwin" ]
then
  ./scripts/homebrew
  ./scripts/macosx
else
  ./scripts/ubuntu
fi

./scripts/node
./scripts/rust

./scripts/netlify
./scripts/func

# Configurations go last so that we fix anything installers mucked up

./scripts/gitconfig
./scripts/sshconfig
./scripts/shell
