#!/bin/sh

if [ `uname` = "Darwin" ]
then
  ./scripts/homebrew
else
  ./scripts/deb
fi

./scripts/zsh
./scripts/gitconfig
./scripts/sshconfig
./scripts/javascript
./scripts/azure
./scripts/rust
./scripts/netlify
./scripts/macosx
./scripts/source
./scripts/shell
