#!/bin/sh

cd $(dirname $0)

if [ `uname` = "Darwin" ]
then
  ./install-homebrew
  ./config-macosx
else
  #./bootstrap-ubuntu
fi

./install-git
./install-node
./install-rust

# make sure that nvm stuff is loaded
source dotfiles/bashrc

./install-netlify
./install-func

./config-ssh
./config-git
./config-bash

if [ `uname` = "Linux" ]
then
  ./update-ubuntu
fi
