#!/bin/sh

if test ! $(which brew)
then
  if [ `uname` = "Linux" ]
  then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  else
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
  fi
fi 

brew upgrade
brew update
brew bundle

# on both
# brew cask install docker

# on Mac
# brew cask install visual-studio-code
# brew cask install notion
# brew cask install google-chrome
# brew cask install slack
# brew cask install microsoft-teams
# brew cask install zoomus

# brew install mas
