#!/bin/bash


cp $(dirname $0)/dotfiles/gitconfig ~/.gitconfig

if [ `uname` = "Darwin" ]
then
  cat $(dirname $0)/dotfiles/gitconfig-osx >> ~/.gitconfig
else
  cat $(dirname $0)/dotfiles/gitconfig-wsl >> ~/.gitconfig
fi
