#!/bin/sh

cp $(dirname $0)/dotfiles/bashrc ~/.bashrc

if [ `uname` = "Darwin" ]
then
cat <<EOF >> ~/.bashrc
alias code="/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin/code"
EOF
fi