#!/bin/bash

cp $(dirname $0)/dot-gitconfig ~/.gitconfig

if [ `uname` = "Darwin" ]
then
  cat $(dirname $0)/dot-gitconfig-osx >> ~/.gitconfig
else
  cat $(dirname $0)/dot-gitconfig-wsl >> ~/.gitconfig
fi
