#!/bin/bash

./install-node

if test ! $(which netlify)
then
  npm install -g netlify-cli
fi

if test ! -f ~/.netlify/helper/bin/git-credential-netlify
then
  netlify plugins:install netlify-lm-plugin
fi
