#!/bin/sh

sudo apt-get install -y git git-lfs jq direnv zsh

if test ! ~/.nvm
then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    source ~/.bashrc
    nvm install --lts
fi