#!/bin/bash

# need to ensure that git lfs install is run?

cat <<EOF > ~/.gitconfig
[filter "lfs"]
  required = true
  clean = git-lfs clean -- %f
  smudge = git-lfs smudge -- %f
  process = git-lfs filter-process

[user]
  name = Duncan Davidson
  email = duncandavidson@me.com

[credential]
  helper = netlify
EOF

if [ `uname` = "Darwin" ]
then
cat <<EOF >> ~/.gitconfig
  helper = osxkeychain
EOF
else
cat <<EOF >> ~/.gitconfig
  helper = "/mnt/c/Program\\\\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"
EOF
fi