#!/bin/bash

if [ ! -d ~/.nvm ]
then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  source $(dirname $0)/../dotfiles/bashrc
  nvm install --lts
fi

npmi() {
  if test $2
  then
    b=$2
  else
    b=$1
  fi
  if test ! $(which $b)
  then
    npm install -g $1
  fi
}

npmi typescript tsc
npmi eslint
npmi jake
npmi prettier