#!/bin/sh

if test ! -d ~/.oh-my-zsh
then
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

cat <<EOF > ~/.zshrc
export ZSH=\$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
source \$ZSH/oh-my-zsh.sh
CASE_SENSITIVE="true"
export PATH="/Users/duncand/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Users/duncand/.netlify/helper/bin"
export NVM_DIR=~/.nvm
source /usr/local/opt/nvm/nvm.sh 
eval "\$(direnv hook zsh)"
EOF

if [ `uname` = "Darwin" ]
then
cat <<EOF >> ~/.zshrc
alias code="/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin/code"
EOF
fi