#!/bin/bash

mkdir -p ~/.ssh

cat <<EOF > ~/.ssh/config
Host *
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
EOF

if [ `uname` = "Darwin" ]
then
cat <<EOF >> ~/.ssh/config
  UseKeychain yes
EOF
fi